### ISSUE TITLE
Fix Ubuntu 16.04 home PETSc

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#139]

**Comment by BenjaminRodenberg** [comment]
Last successful run: https://travis-ci.org/precice/systemtests/builds/621545880

**Comment by BenjaminRodenberg** [comment]
Building PETSc from source the [unit tests succeed](https://travis-ci.com/BenjaminRueth/systemtests/jobs/283877761). I created a [branch on my fork](https://github.com/BenjaminRueth/systemtests/tree/petsc_from_src) with a modified [`Dockerfile.Ubuntu1604.home`](https://github.com/BenjaminRueth/systemtests/blob/2178e8a789d132a9c1bf714540b50e942bc2ebf9/precice/Dockerfile.Ubuntu1604.home).

Note that building PETSc from source is not a solution but a workaround, since we want to be able to use PETSc provided via `apt` (and we should test it). However, it might be useful to provide an additional test, where PETSc is built from source. I would suggest to wait for the outcome of https://github.com/precice/precice/issues/667 before adding any new tests.

**Comment by Eder-K** [comment]
With #222 , Ubuntu 16.04 is no longer tested. For newer Ubuntu versions, the PETSc builds now succeed with #246 .
Regardless of this, we do now successfully use PETSc from `apt` in 20.04 builds. Note that this is not possible in 18.04, as `apt` only provides PETSc v3.6, whereby we require at least PETSc v3.12. Due to this we continue to build PETSc from source in 18.04 builds.
