### ISSUE TITLE
Fix existing systemtests for Ubuntu18.04

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/systemtests#17]
currently most systemtests only work with Ubuntu16.04. We should fix this, such that it also works with Ubuntu 18.04

Works with Ubuntu18.04:

- [x] [OpenFOAM-OpenFOAM](https://github.com/precice/systemtests/tree/master/Test_of-of.Ubuntu1604)
- [x] [OpenFOAM-CalculiX](https://github.com/precice/systemtests/tree/master/Test_of-ccx.Ubuntu1604)
- [x] [SU2-CalculiX](https://github.com/precice/systemtests/tree/master/Test_su2-ccx.Ubuntu1604)

**Comment by shkodm** [comment]
### Update on the issue: 

I fixed building of all tests, however it seems that output do not match reference results. Results can be found in this [repo](https://github.com/shkodm/precice_st_output/tree/master/Ubuntu1804) and full travis build with tests for both 16.04 and 18.04 is [here]( https://travis-ci.org/shkodm/systemtests/builds/462432218 ).

#### OpenFOAM based systemtests

For systemtests, that use openFOAM, since 18.04 is not supported by openFOAM4 (see [here](https://openfoam.org/download/4-0-ubuntu/) )  I used openFOAM5. So I guess results might be different. I don't have any experience with openFOAM adapter, so it is hard to analyze if this is possible. @MakisH , do you have any suggestions here? Should we take new results as the new "reference results"?  
*  For Calculix-openFOAM the error is ( [log file](https://api.travis-ci.org/v3/job/462432224/log.txt) )
> `Files differing               : []
Files only in reference (left): ['1', '4', '2', '5', '3', 'polyMesh', '1', '4', '2', '5', '3', 'polyMesh']
Files only in output(right)   : []

*   For openFOAM-openFOAM the error is ( [log file]( https://api.travis-ci.org/v3/job/462432223/log.txt)) 
> Files differing               : ['gradTy', 'gradTz', 'gradTx', 'T', 'time', 'gradTy', 'gradTz', 'gradTx', 'T', 'time', 'faces', 'owner', 'neighbour', 'boundary', 'points', 'gradTy', 'gradTz', 'gradTx', 'T', 'time', 'gradTy', 'gradTz', 'gradTx', 'T', 'time', 'gradTy', 'gradTz', 'gradTx', 'T', 'time', 'T', 'p_rgh', 'phi', 'p', 'U', 'time', 'T', 'p_rgh', 'phi', 'p', 'U', 'time', 'faces', 'owner', 'neighbour', 'boundary', 'points', 'T', 'p_rgh', 'phi', 'p', 'U', 'time', 'T', 'p_rgh', 'phi', 'p', 'U', 'time', 'T', 'p_rgh', 'phi', 'p', 'U', 'time']
Files only in reference (left): []
Files only in output(right)   : []

#### SU2-Calculix 

For SU2-Calculix tests, apart from the bug in the Calculix makefile, nothing was changed.  Quite a lot of resultant files seems to be different.  Log file from the build and run on Travis can be found [here](https://api.travis-ci.org/v3/job/462432222/log.txt) (Scroll to bottom for the relevant stuff, it is too much to paste here). Visualization in the ParaView shows no difference between results. So not clear why files are different.

**Comment by MakisH** [comment]
> For systemtests, that use openFOAM, since 18.04 is not supported by openFOAM4 (see here ) I used openFOAM5. So I guess results might be different. I don't have any experience with openFOAM adapter, so it is hard to analyze if this is possible. @MakisH , do you have any suggestions here? Should we take new results as the new "reference results"?

All these are result files and seem to be different. Is it that the results are different, or are there differences in time etc? Could you please run a diff and see what's happening? If we don't ignore timestamps and runtime, the result files will always be different.

Where do we have OpenFOAM 4.0? Everywhere it should be OpenFOAM 5.0, as both tutorial cases are prepared for this version at the moment.

**Comment by shkodm** [comment]
We have openFOAM 4 both here https://github.com/precice/systemtests/blob/0369fdc8d3d52a231811b0c0149696fe8efe8682/Test_of-ccx.Ubuntu1604/Dockerfile#L26
and here: 
https://github.com/precice/systemtests/blob/0369fdc8d3d52a231811b0c0149696fe8efe8682/Test_of-of.Ubuntu1604/Dockerfile#L20

Actually, maybe it is indeed just difference, because in results files something like openFOAM4 or openFOAM5 is written. Or due to different times. I will check and update

**Comment by shkodm** [comment]
#### Update

Upon `vimdiff`-ing around,  It seems that for openFOAM < - > openFOAM and SU2< - > Calculix difference in  results do exist, but quite small ( in terms of some non-significant floating point digits ). Also, as I assumed openfoam4 and openfoam5 use different headers for the results, which makes files different. 

What is still not clear, is the difference for the openFOAM <-> CalculiX coupling. For that case, reference output has several folders of files, that are simply not present in the output of run on 18.04.

**Comment by BenjaminRodenberg** [comment]
Status of this issue?

**Comment by shkodm** [comment]
It is pretty trivial to add, so should be implemented in the future

**Comment by Eder-K** [comment]
Didn't get around to cleaning this issue up until now, oops. Anyways, this has been resolved for a long time, presumably with the large sweep of fixes in #148 at the latest.
