### ISSUE TITLE
SU2 - CCX test fail building

### ISSUE THREAD

**Issue by floli** [precice/systemtests#63]
Using latest `master` at 4d9603bbbe74424e031b4388d7e3de16c5be4bc9

Docker 18.09.3, Linux 5.0.4.

```
mpicc -Wall -O3 -fopenmp -I./ -I./adapter -I/CalculiX/ccx_2.15/src -I/spooles.2.2 -I/precice/src -I/usr/local/ARPACK  -DARCH="Linux" -DSPOOLES -DARPACK -DMATRIXSTORAGE -c adapter/PreciceInterface.c -o bin/PreciceInterface.o
adapter/PreciceInterface.c:13:38: fatal error: precice/SolverInterfaceC.h: No such file or directory
compilation terminated.
Makefile:65: recipe for target 'bin/PreciceInterface.o' failed
make: *** [bin/PreciceInterface.o] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```
Complete console output: [Output.txt](https://github.com/precice/systemtests/files/3004385/Output.txt)

**Comment by floli** [comment]
Very similar error for the `of-ccx` test.

**Comment by shkodm** [comment]
It started failing after  [this PR](https://github.com/precice/calculix-adapter/pull/14/files), where port to CMake installation was done.

**Comment by MakisH** [comment]
The SU2 adapter is still assuming SCons, since [this PR](https://github.com/precice/su2-adapter/pull/6) is awaiting review.

For the CalculiX adapter, make sure to set the `PKG_CONFIG_PATH`, if needed. Also, make sure to use preCICE as a shared library, as the dependencies for static linking are not yet defined in our `libprecice.pc`.
